version: "3.4"
services:
  server:
    build:
      context: .
      target: prod
    ports:
      - "8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./app:/app
  test-server:
    build:
      context: .
      target: test
    volumes:
      - ./app:/data/app
      - ./spec:/data/spec